import 'package:flutter/material.dart';
import '../../widgets/app_drawer.dart';
import '../../utils/constants.dart';

class SupportScreen extends StatelessWidget {
  const SupportScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    bool isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      appBar: AppBar(title: const Text('Help & Support')),
      drawer: const AppDrawer(),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Container(
              padding: const EdgeInsets.all(32),
              decoration: BoxDecoration(color: Theme.of(context).cardColor, borderRadius: BorderRadius.circular(20), boxShadow: [BoxShadow(color: Colors.black.withOpacity(isDark ? 0.3 : 0.05), blurRadius: 10, offset: const Offset(0, 5))]),
              child: const Column(
                children: [
                  Icon(Icons.support_agent, size: 80, color: AppColors.primary),
                  SizedBox(height: 16),
                  Text('How can we help you?', textAlign: TextAlign.center, style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
                ],
              ),
            ),
            const SizedBox(height: 32),
            const Text('Frequently Asked Questions', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
            const SizedBox(height: 16),
            _buildFaqTile('How are eco points calculated?', 'Points are assigned directly via the sustainability impact algorithms assigned to each predefined task. Custom tasks are evaluated dynamically.', isDark, context),
            _buildFaqTile('Can I undo a marked habit?', 'Currently, daily marks are tracked sequentially. If you make a mistake, it cannot easily be reverted right now without clearing history.', isDark, context),
            _buildFaqTile('How is my impact measured?', 'Impact is generated by taking your completed days and multiplying it by the metric value allocated to the task item.', isDark, context),
            const SizedBox(height: 48),
            ElevatedButton.icon(
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Opening mail client to: support@ecoroutine.app')));
                // Logic to open mailto:support@ecoroutine.app
              },
              icon: const Icon(Icons.email, color: Colors.white),
              label: const Text('Contact Support via Email', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white)),
              style: ElevatedButton.styleFrom(
                padding: const EdgeInsets.symmetric(vertical: 18),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                backgroundColor: AppColors.primary,
              ),
            )
          ],
        ),
      ),
    );
  }

  Widget _buildFaqTile(String question, String answer, bool isDark, BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(color: Theme.of(context).cardColor, borderRadius: BorderRadius.circular(16)),
      child: ExpansionTile(
        title: Text(question, style: TextStyle(fontWeight: FontWeight.bold, color: isDark ? Colors.white : AppColors.textPrimary)),
        iconColor: AppColors.primary,
        childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
        children: [
          Text(answer, style: TextStyle(color: isDark ? Colors.white70 : AppColors.textSecondary, height: 1.5)),
        ],
      ),
    );
  }
}
